//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFramework.Statics
{
    
    public class SFResAssets
    {
        public const string App_gamesuccess_sfp_GameSuccessView_prefab = "app_gamesuccess.sfp/GameSuccessView";
        public const string App_guide_sfp_GuideLevel1_prefab = "app_guide.sfp/GuideLevel1";
        public const string App_hudmain_sfp_HudMainView_prefab = "app_hudmain.sfp/HudMainView";
        public const string App_mainscene_sfp_Branch_prefab = "app_mainscene.sfp/Branch";
        public const string App_mainscene_sfp_GuideCircle_png = "app_mainscene.sfp/GuideCircle";
        public const string App_mainscene_sfp_Guidemask_png = "app_mainscene.sfp/Guidemask";
        public const string App_mainscene_sfp_img_mud_png = "app_mainscene.sfp/img_mud";
        public const string App_mainscene_sfp_Pig_prefab = "app_mainscene.sfp/Pig";
        public const string App_mainscene_sfp_SceneBg_png = "app_mainscene.sfp/SceneBg";
        public const string App_mainscene_sfs_MainSceneView_unity = "app_mainscene.sfs/MainSceneView";
        public const string App_pigs_pig1_sfp_pig1_atlas_txt = "app_pigs_pig1.sfp/pig1.atlas";
        public const string App_pigs_pig1_sfp_pig1_png = "app_pigs_pig1.sfp/pig1";
        public const string App_pigs_pig1_sfp_pig1_skel_bytes = "app_pigs_pig1.sfp/pig1.skel";
        public const string App_pigs_pig1_sfp_pig1_Atlas_asset = "app_pigs_pig1.sfp/pig1_Atlas";
        public const string App_pigs_pig1_sfp_pig1_Material_mat = "app_pigs_pig1.sfp/pig1_Material";
        public const string App_pigs_pig1_sfp_pig1_SkeletonData_asset = "app_pigs_pig1.sfp/pig1_SkeletonData";
        public const string App_pigs_pig2_sfp_pig2_atlas_txt = "app_pigs_pig2.sfp/pig2.atlas";
        public const string App_pigs_pig2_sfp_pig2_png = "app_pigs_pig2.sfp/pig2";
        public const string App_pigs_pig2_sfp_pig2_skel_bytes = "app_pigs_pig2.sfp/pig2.skel";
        public const string App_pigs_pig2_sfp_pig2_Atlas_asset = "app_pigs_pig2.sfp/pig2_Atlas";
        public const string App_pigs_pig2_sfp_pig2_Material_mat = "app_pigs_pig2.sfp/pig2_Material";
        public const string App_pigs_pig2_sfp_pig2_SkeletonData_asset = "app_pigs_pig2.sfp/pig2_SkeletonData";
        public const string App_pigs_pig3_sfp_pig3_atlas_txt = "app_pigs_pig3.sfp/pig3.atlas";
        public const string App_pigs_pig3_sfp_pig3_png = "app_pigs_pig3.sfp/pig3";
        public const string App_pigs_pig3_sfp_pig3_skel_bytes = "app_pigs_pig3.sfp/pig3.skel";
        public const string App_pigs_pig3_sfp_pig3_Atlas_asset = "app_pigs_pig3.sfp/pig3_Atlas";
        public const string App_pigs_pig3_sfp_pig3_Material_mat = "app_pigs_pig3.sfp/pig3_Material";
        public const string App_pigs_pig3_sfp_pig3_SkeletonData_asset = "app_pigs_pig3.sfp/pig3_SkeletonData";
        public const string App_pigs_pig4_sfp_pig4_atlas_txt = "app_pigs_pig4.sfp/pig4.atlas";
        public const string App_pigs_pig4_sfp_pig4_png = "app_pigs_pig4.sfp/pig4";
        public const string App_pigs_pig4_sfp_pig4_skel_bytes = "app_pigs_pig4.sfp/pig4.skel";
        public const string App_pigs_pig4_sfp_pig4_Atlas_asset = "app_pigs_pig4.sfp/pig4_Atlas";
        public const string App_pigs_pig4_sfp_pig4_Material_mat = "app_pigs_pig4.sfp/pig4_Material";
        public const string App_pigs_pig4_sfp_pig4_SkeletonData_asset = "app_pigs_pig4.sfp/pig4_SkeletonData";
        public const string App_pigs_pig5_sfp_pig5_atlas_txt = "app_pigs_pig5.sfp/pig5.atlas";
        public const string App_pigs_pig5_sfp_pig5_png = "app_pigs_pig5.sfp/pig5";
        public const string App_pigs_pig5_sfp_pig5_skel_bytes = "app_pigs_pig5.sfp/pig5.skel";
        public const string App_pigs_pig5_sfp_pig5_Atlas_asset = "app_pigs_pig5.sfp/pig5_Atlas";
        public const string App_pigs_pig5_sfp_pig5_Material_mat = "app_pigs_pig5.sfp/pig5_Material";
        public const string App_pigs_pig5_sfp_pig5_SkeletonData_asset = "app_pigs_pig5.sfp/pig5_SkeletonData";
        public const string App_pigs_pig6_sfp_pig6_atlas_txt = "app_pigs_pig6.sfp/pig6.atlas";
        public const string App_pigs_pig6_sfp_pig6_png = "app_pigs_pig6.sfp/pig6";
        public const string App_pigs_pig6_sfp_pig6_skel_bytes = "app_pigs_pig6.sfp/pig6.skel";
        public const string App_pigs_pig6_sfp_pig6_Atlas_asset = "app_pigs_pig6.sfp/pig6_Atlas";
        public const string App_pigs_pig6_sfp_pig6_Material_mat = "app_pigs_pig6.sfp/pig6_Material";
        public const string App_pigs_pig6_sfp_pig6_SkeletonData_asset = "app_pigs_pig6.sfp/pig6_SkeletonData";
        public const string App_pigs_pig7_sfp_pig7_atlas_txt = "app_pigs_pig7.sfp/pig7.atlas";
        public const string App_pigs_pig7_sfp_pig7_png = "app_pigs_pig7.sfp/pig7";
        public const string App_pigs_pig7_sfp_pig7_skel_bytes = "app_pigs_pig7.sfp/pig7.skel";
        public const string App_pigs_pig7_sfp_pig7_Atlas_asset = "app_pigs_pig7.sfp/pig7_Atlas";
        public const string App_pigs_pig7_sfp_pig7_Material_mat = "app_pigs_pig7.sfp/pig7_Material";
        public const string App_pigs_pig7_sfp_pig7_SkeletonData_asset = "app_pigs_pig7.sfp/pig7_SkeletonData";
        public const string App_pigs_pig8_sfp_pig8_atlas_txt = "app_pigs_pig8.sfp/pig8.atlas";
        public const string App_pigs_pig8_sfp_pig8_png = "app_pigs_pig8.sfp/pig8";
        public const string App_pigs_pig8_sfp_pig8_skel_bytes = "app_pigs_pig8.sfp/pig8.skel";
        public const string App_pigs_pig8_sfp_pig8_Atlas_asset = "app_pigs_pig8.sfp/pig8_Atlas";
        public const string App_pigs_pig8_sfp_pig8_Material_mat = "app_pigs_pig8.sfp/pig8_Material";
        public const string App_pigs_pig8_sfp_pig8_SkeletonData_asset = "app_pigs_pig8.sfp/pig8_SkeletonData";
        public const string App_pigs_pig9_sfp_pig9_atlas_txt = "app_pigs_pig9.sfp/pig9.atlas";
        public const string App_pigs_pig9_sfp_pig9_png = "app_pigs_pig9.sfp/pig9";
        public const string App_pigs_pig9_sfp_pig9_skel_bytes = "app_pigs_pig9.sfp/pig9.skel";
        public const string App_pigs_pig9_sfp_pig9_Atlas_asset = "app_pigs_pig9.sfp/pig9_Atlas";
        public const string App_pigs_pig9_sfp_pig9_Material_mat = "app_pigs_pig9.sfp/pig9_Material";
        public const string App_pigs_pig9_sfp_pig9_SkeletonData_asset = "app_pigs_pig9.sfp/pig9_SkeletonData";
        public const string App_pigs_pig10_sfp_pig10_atlas_txt = "app_pigs_pig10.sfp/pig10.atlas";
        public const string App_pigs_pig10_sfp_pig10_png = "app_pigs_pig10.sfp/pig10";
        public const string App_pigs_pig10_sfp_pig10_skel_bytes = "app_pigs_pig10.sfp/pig10.skel";
        public const string App_pigs_pig10_sfp_pig10_Atlas_asset = "app_pigs_pig10.sfp/pig10_Atlas";
        public const string App_pigs_pig10_sfp_pig10_Material_mat = "app_pigs_pig10.sfp/pig10_Material";
        public const string App_pigs_pig10_sfp_pig10_SkeletonData_asset = "app_pigs_pig10.sfp/pig10_SkeletonData";
        public const string App_pigs_pig11_sfp_pig11_atlas_txt = "app_pigs_pig11.sfp/pig11.atlas";
        public const string App_pigs_pig11_sfp_pig11_png = "app_pigs_pig11.sfp/pig11";
        public const string App_pigs_pig11_sfp_pig11_skel_bytes = "app_pigs_pig11.sfp/pig11.skel";
        public const string App_pigs_pig11_sfp_pig11_Atlas_asset = "app_pigs_pig11.sfp/pig11_Atlas";
        public const string App_pigs_pig11_sfp_pig11_Material_mat = "app_pigs_pig11.sfp/pig11_Material";
        public const string App_pigs_pig11_sfp_pig11_SkeletonData_asset = "app_pigs_pig11.sfp/pig11_SkeletonData";
        public const string App_snipe_sfp_SnipeView_prefab = "app_snipe.sfp/SnipeView";
        public const string Sfscene_sfs_SFSCENE_scenetemplate = "sfscene.sfs/SFSCENE";
        public const string Suiroot_sfp_SUIROOT_prefab = "suiroot.sfp/SUIROOT";
        public const string Suiroot_sfp_SUIROOTURP_prefab = "suiroot.sfp/SUIROOTURP";
    }
    public class App_gamesuccess_sfp
    {
        public const string BundleName = "app_gamesuccess.sfp";
        public const string RES_GameSuccessView_prefab = "GameSuccessView";
    }
    public class App_guide
    {
        public const string BundleName = "app_guide";
    }
    public class App_guide_sfp
    {
        public const string BundleName = "app_guide.sfp";
        public const string RES_GuideLevel1_prefab = "GuideLevel1";
    }
    public class App_hudmain_sfp
    {
        public const string BundleName = "app_hudmain.sfp";
        public const string RES_HudMainView_prefab = "HudMainView";
    }
    public class App_mainscene_sfp
    {
        public const string BundleName = "app_mainscene.sfp";
        public const string RES_Branch_prefab = "Branch";
        public const string RES_GuideCircle_png = "GuideCircle";
        public const string RES_Guidemask_png = "Guidemask";
        public const string RES_img_mud_png = "img_mud";
        public const string RES_Pig_prefab = "Pig";
        public const string RES_SceneBg_png = "SceneBg";
    }
    public class App_mainscene_sfs
    {
        public const string BundleName = "app_mainscene.sfs";
        public const string RES_MainSceneView_unity = "MainSceneView";
    }
    public class App_pigs_pig1_sfp
    {
        public const string BundleName = "app_pigs_pig1.sfp";
        public const string RES_pig1_atlas_txt = "pig1.atlas";
        public const string RES_pig1_png = "pig1";
        public const string RES_pig1_skel_bytes = "pig1.skel";
        public const string RES_pig1_Atlas_asset = "pig1_Atlas";
        public const string RES_pig1_Material_mat = "pig1_Material";
        public const string RES_pig1_SkeletonData_asset = "pig1_SkeletonData";
    }
    public class App_pigs_pig2_sfp
    {
        public const string BundleName = "app_pigs_pig2.sfp";
        public const string RES_pig2_atlas_txt = "pig2.atlas";
        public const string RES_pig2_png = "pig2";
        public const string RES_pig2_skel_bytes = "pig2.skel";
        public const string RES_pig2_Atlas_asset = "pig2_Atlas";
        public const string RES_pig2_Material_mat = "pig2_Material";
        public const string RES_pig2_SkeletonData_asset = "pig2_SkeletonData";
    }
    public class App_pigs_pig3_sfp
    {
        public const string BundleName = "app_pigs_pig3.sfp";
        public const string RES_pig3_atlas_txt = "pig3.atlas";
        public const string RES_pig3_png = "pig3";
        public const string RES_pig3_skel_bytes = "pig3.skel";
        public const string RES_pig3_Atlas_asset = "pig3_Atlas";
        public const string RES_pig3_Material_mat = "pig3_Material";
        public const string RES_pig3_SkeletonData_asset = "pig3_SkeletonData";
    }
    public class App_pigs_pig4_sfp
    {
        public const string BundleName = "app_pigs_pig4.sfp";
        public const string RES_pig4_atlas_txt = "pig4.atlas";
        public const string RES_pig4_png = "pig4";
        public const string RES_pig4_skel_bytes = "pig4.skel";
        public const string RES_pig4_Atlas_asset = "pig4_Atlas";
        public const string RES_pig4_Material_mat = "pig4_Material";
        public const string RES_pig4_SkeletonData_asset = "pig4_SkeletonData";
    }
    public class App_pigs_pig5_sfp
    {
        public const string BundleName = "app_pigs_pig5.sfp";
        public const string RES_pig5_atlas_txt = "pig5.atlas";
        public const string RES_pig5_png = "pig5";
        public const string RES_pig5_skel_bytes = "pig5.skel";
        public const string RES_pig5_Atlas_asset = "pig5_Atlas";
        public const string RES_pig5_Material_mat = "pig5_Material";
        public const string RES_pig5_SkeletonData_asset = "pig5_SkeletonData";
    }
    public class App_pigs_pig6_sfp
    {
        public const string BundleName = "app_pigs_pig6.sfp";
        public const string RES_pig6_atlas_txt = "pig6.atlas";
        public const string RES_pig6_png = "pig6";
        public const string RES_pig6_skel_bytes = "pig6.skel";
        public const string RES_pig6_Atlas_asset = "pig6_Atlas";
        public const string RES_pig6_Material_mat = "pig6_Material";
        public const string RES_pig6_SkeletonData_asset = "pig6_SkeletonData";
    }
    public class App_pigs_pig7_sfp
    {
        public const string BundleName = "app_pigs_pig7.sfp";
        public const string RES_pig7_atlas_txt = "pig7.atlas";
        public const string RES_pig7_png = "pig7";
        public const string RES_pig7_skel_bytes = "pig7.skel";
        public const string RES_pig7_Atlas_asset = "pig7_Atlas";
        public const string RES_pig7_Material_mat = "pig7_Material";
        public const string RES_pig7_SkeletonData_asset = "pig7_SkeletonData";
    }
    public class App_pigs_pig8_sfp
    {
        public const string BundleName = "app_pigs_pig8.sfp";
        public const string RES_pig8_atlas_txt = "pig8.atlas";
        public const string RES_pig8_png = "pig8";
        public const string RES_pig8_skel_bytes = "pig8.skel";
        public const string RES_pig8_Atlas_asset = "pig8_Atlas";
        public const string RES_pig8_Material_mat = "pig8_Material";
        public const string RES_pig8_SkeletonData_asset = "pig8_SkeletonData";
    }
    public class App_pigs_pig9_sfp
    {
        public const string BundleName = "app_pigs_pig9.sfp";
        public const string RES_pig9_atlas_txt = "pig9.atlas";
        public const string RES_pig9_png = "pig9";
        public const string RES_pig9_skel_bytes = "pig9.skel";
        public const string RES_pig9_Atlas_asset = "pig9_Atlas";
        public const string RES_pig9_Material_mat = "pig9_Material";
        public const string RES_pig9_SkeletonData_asset = "pig9_SkeletonData";
    }
    public class App_pigs_pig10_sfp
    {
        public const string BundleName = "app_pigs_pig10.sfp";
        public const string RES_pig10_atlas_txt = "pig10.atlas";
        public const string RES_pig10_png = "pig10";
        public const string RES_pig10_skel_bytes = "pig10.skel";
        public const string RES_pig10_Atlas_asset = "pig10_Atlas";
        public const string RES_pig10_Material_mat = "pig10_Material";
        public const string RES_pig10_SkeletonData_asset = "pig10_SkeletonData";
    }
    public class App_pigs_pig11_sfp
    {
        public const string BundleName = "app_pigs_pig11.sfp";
        public const string RES_pig11_atlas_txt = "pig11.atlas";
        public const string RES_pig11_png = "pig11";
        public const string RES_pig11_skel_bytes = "pig11.skel";
        public const string RES_pig11_Atlas_asset = "pig11_Atlas";
        public const string RES_pig11_Material_mat = "pig11_Material";
        public const string RES_pig11_SkeletonData_asset = "pig11_SkeletonData";
    }
    public class App_snipe_sfp
    {
        public const string BundleName = "app_snipe.sfp";
        public const string RES_SnipeView_prefab = "SnipeView";
    }
    public class Sfscene_sfs
    {
        public const string BundleName = "sfscene.sfs";
        public const string RES_SFSCENE_scenetemplate = "SFSCENE";
    }
    public class Suiroot_sfp
    {
        public const string BundleName = "suiroot.sfp";
        public const string RES_SUIROOT_prefab = "SUIROOT";
        public const string RES_SUIROOTURP_prefab = "SUIROOTURP";
    }
}
