//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFramework.Statics
{
    
    public class SFStaticsControl
    {
        public const string App_Tips_TipsControl = "App.Tips.TipsControl";
        public const string App_Snipe_SnipeControl = "App.Snipe.SnipeControl";
        public const string App_SelectArea_SelectAreaControl = "App.SelectArea.SelectAreaControl";
        public const string App_NetLoading_NetLoadingControl = "App.NetLoading.NetLoadingControl";
        public const string App_MainScene_MainSceneControl = "App.MainScene.MainSceneControl";
        public const string App_Language_LanguageControl = "App.Language.LanguageControl";
        public const string App_Inventory_InventoryControl = "App.Inventory.InventoryControl";
        public const string App_HudMain_HudMainControl = "App.HudMain.HudMainControl";
        public const string App_Home_HomeControl = "App.Home.HomeControl";
        public const string App_Home_HomeMenuControl = "App.Home.HomeMenuControl";
        public const string App_Guide_GuideControl = "App.Guide.GuideControl";
        public const string App_GameSuccess_GameSuccessControl = "App.GameSuccess.GameSuccessControl";
    }
}
