# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Items_Base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10Items_Base.proto\x12\x11\x43onfig.Items_Base\"4\n\nItems_Base\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0c\n\x04\x41nim\x18\x03 \x01(\t\"\xd2\x01\n\x10Items_Base_datas\x12\x41\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\x30.Config.Items_Base.Items_Base_datas.DatamapEntry\x12,\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x1d.Config.Items_Base.Items_Base\x1aM\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.Config.Items_Base.Items_Base:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Items_Base_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ITEMS_BASE_DATAS_DATAMAPENTRY._options = None
  _ITEMS_BASE_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_ITEMS_BASE']._serialized_start=39
  _globals['_ITEMS_BASE']._serialized_end=91
  _globals['_ITEMS_BASE_DATAS']._serialized_start=94
  _globals['_ITEMS_BASE_DATAS']._serialized_end=304
  _globals['_ITEMS_BASE_DATAS_DATAMAPENTRY']._serialized_start=227
  _globals['_ITEMS_BASE_DATAS_DATAMAPENTRY']._serialized_end=304
# @@protoc_insertion_point(module_scope)
