# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Language_Base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Language_Base.proto\x12\x14\x43onfig.Language_Base\"W\n\rLanguage_Base\x12\x0c\n\x04Name\x18\x01 \x01(\t\x12\x0f\n\x07zh_Hans\x18\x02 \x01(\t\x12\x0f\n\x07zh_Hant\x18\x03 \x01(\t\x12\n\n\x02\x65n\x18\x04 \x01(\t\x12\n\n\x02ja\x18\x05 \x01(\t\"\xe7\x01\n\x13Language_Base_datas\x12G\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\x36.Config.Language_Base.Language_Base_datas.DatamapEntry\x12\x32\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32#.Config.Language_Base.Language_Base\x1aS\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.Config.Language_Base.Language_Base:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Language_Base_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LANGUAGE_BASE_DATAS_DATAMAPENTRY._options = None
  _LANGUAGE_BASE_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_LANGUAGE_BASE']._serialized_start=45
  _globals['_LANGUAGE_BASE']._serialized_end=132
  _globals['_LANGUAGE_BASE_DATAS']._serialized_start=135
  _globals['_LANGUAGE_BASE_DATAS']._serialized_end=366
  _globals['_LANGUAGE_BASE_DATAS_DATAMAPENTRY']._serialized_start=283
  _globals['_LANGUAGE_BASE_DATAS_DATAMAPENTRY']._serialized_end=366
# @@protoc_insertion_point(module_scope)
