# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Levels_Detail.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13Levels_Detail.proto\x12\x14\x43onfig.Levels_Detail\"t\n\rLevels_Detail\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0f\n\x07LevelID\x18\x02 \x01(\x05\x12\r\n\x05Index\x18\x03 \x01(\x05\x12\r\n\x05Items\x18\x04 \x03(\x05\x12\x12\n\nCanAddItem\x18\x05 \x01(\x08\x12\x14\n\x0cRemainPigNum\x18\x06 \x01(\x05\"\xe7\x01\n\x13Levels_Detail_datas\x12G\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\x36.Config.Levels_Detail.Levels_Detail_datas.DatamapEntry\x12\x32\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32#.Config.Levels_Detail.Levels_Detail\x1aS\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.Config.Levels_Detail.Levels_Detail:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Levels_Detail_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEVELS_DETAIL_DATAS_DATAMAPENTRY._options = None
  _LEVELS_DETAIL_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_LEVELS_DETAIL']._serialized_start=45
  _globals['_LEVELS_DETAIL']._serialized_end=161
  _globals['_LEVELS_DETAIL_DATAS']._serialized_start=164
  _globals['_LEVELS_DETAIL_DATAS']._serialized_end=395
  _globals['_LEVELS_DETAIL_DATAS_DATAMAPENTRY']._serialized_start=312
  _globals['_LEVELS_DETAIL_DATAS_DATAMAPENTRY']._serialized_end=395
# @@protoc_insertion_point(module_scope)
