# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Levels_Area.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11Levels_Area.proto\x12\x12\x43onfig.Levels_Area\"6\n\x0bLevels_Area\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\r\n\x05Group\x18\x03 \x01(\t\"\xd9\x01\n\x11Levels_Area_datas\x12\x43\n\x07\x64\x61tamap\x18\x01 \x03(\x0b\x32\x32.Config.Levels_Area.Levels_Area_datas.DatamapEntry\x12.\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\x1f.Config.Levels_Area.Levels_Area\x1aO\n\x0c\x44\x61tamapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12.\n\x05value\x18\x02 \x01(\x0b\x32\x1f.Config.Levels_Area.Levels_Area:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Levels_Area_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LEVELS_AREA_DATAS_DATAMAPENTRY._options = None
  _LEVELS_AREA_DATAS_DATAMAPENTRY._serialized_options = b'8\001'
  _globals['_LEVELS_AREA']._serialized_start=41
  _globals['_LEVELS_AREA']._serialized_end=95
  _globals['_LEVELS_AREA_DATAS']._serialized_start=98
  _globals['_LEVELS_AREA_DATAS']._serialized_end=315
  _globals['_LEVELS_AREA_DATAS_DATAMAPENTRY']._serialized_start=236
  _globals['_LEVELS_AREA_DATAS_DATAMAPENTRY']._serialized_end=315
# @@protoc_insertion_point(module_scope)
