// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Levels_Base.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config.LevelsBase {

  /// <summary>Holder for reflection information generated from Levels_Base.proto</summary>
  public static partial class LevelsBaseReflection {

    #region Descriptor
    /// <summary>File descriptor for Levels_Base.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LevelsBaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFMZXZlbHNfQmFzZS5wcm90bxISQ29uZmlnLkxldmVsc19CYXNlIqABCgtM",
            "ZXZlbHNfQmFzZRIKCgJJRBgBIAEoBRIPCgdBbGxUeXBzGAIgAygFEg8KB0Fs",
            "bE51bXMYAyADKAUSEQoJQWZ0ZXJUeXBzGAQgAygFEhAKCEFmdGVyTnVtGAUg",
            "AygFEhMKC1RyaWdnZXJUeXBlGAYgAygFEg0KBUZsb29yGAcgASgFEgwKBE5h",
            "bWUYCCABKAkSDAoERGVzYxgJIAEoCSLZAQoRTGV2ZWxzX0Jhc2VfZGF0YXMS",
            "QwoHZGF0YW1hcBgBIAMoCzIyLkNvbmZpZy5MZXZlbHNfQmFzZS5MZXZlbHNf",
            "QmFzZV9kYXRhcy5EYXRhbWFwRW50cnkSLgoFZGF0YXMYAiADKAsyHy5Db25m",
            "aWcuTGV2ZWxzX0Jhc2UuTGV2ZWxzX0Jhc2UaTwoMRGF0YW1hcEVudHJ5EgsK",
            "A2tleRgBIAEoBRIuCgV2YWx1ZRgCIAEoCzIfLkNvbmZpZy5MZXZlbHNfQmFz",
            "ZS5MZXZlbHNfQmFzZToCOAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.LevelsBase.Levels_Base), global::Config.LevelsBase.Levels_Base.Parser, new[]{ "ID", "AllTyps", "AllNums", "AfterTyps", "AfterNum", "TriggerType", "Floor", "Name", "Desc" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.LevelsBase.Levels_Base_datas), global::Config.LevelsBase.Levels_Base_datas.Parser, new[]{ "Datamap", "Datas" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Levels_Base : pb::IMessage<Levels_Base>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Levels_Base> _parser = new pb::MessageParser<Levels_Base>(() => new Levels_Base());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Levels_Base> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.LevelsBase.LevelsBaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base(Levels_Base other) : this() {
      iD_ = other.iD_;
      allTyps_ = other.allTyps_.Clone();
      allNums_ = other.allNums_.Clone();
      afterTyps_ = other.afterTyps_.Clone();
      afterNum_ = other.afterNum_.Clone();
      triggerType_ = other.triggerType_.Clone();
      floor_ = other.floor_;
      name_ = other.name_;
      desc_ = other.desc_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base Clone() {
      return new Levels_Base(this);
    }

    /// <summary>Field number for the "ID" field.</summary>
    public const int IDFieldNumber = 1;
    private int iD_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ID {
      get { return iD_; }
      set {
        iD_ = value;
      }
    }

    /// <summary>Field number for the "AllTyps" field.</summary>
    public const int AllTypsFieldNumber = 2;
    private static readonly pb::FieldCodec<int> _repeated_allTyps_codec
        = pb::FieldCodec.ForInt32(18);
    private readonly pbc::RepeatedField<int> allTyps_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AllTyps {
      get { return allTyps_; }
    }

    /// <summary>Field number for the "AllNums" field.</summary>
    public const int AllNumsFieldNumber = 3;
    private static readonly pb::FieldCodec<int> _repeated_allNums_codec
        = pb::FieldCodec.ForInt32(26);
    private readonly pbc::RepeatedField<int> allNums_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AllNums {
      get { return allNums_; }
    }

    /// <summary>Field number for the "AfterTyps" field.</summary>
    public const int AfterTypsFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_afterTyps_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> afterTyps_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AfterTyps {
      get { return afterTyps_; }
    }

    /// <summary>Field number for the "AfterNum" field.</summary>
    public const int AfterNumFieldNumber = 5;
    private static readonly pb::FieldCodec<int> _repeated_afterNum_codec
        = pb::FieldCodec.ForInt32(42);
    private readonly pbc::RepeatedField<int> afterNum_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> AfterNum {
      get { return afterNum_; }
    }

    /// <summary>Field number for the "TriggerType" field.</summary>
    public const int TriggerTypeFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_triggerType_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> triggerType_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> TriggerType {
      get { return triggerType_; }
    }

    /// <summary>Field number for the "Floor" field.</summary>
    public const int FloorFieldNumber = 7;
    private int floor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Floor {
      get { return floor_; }
      set {
        floor_ = value;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 8;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Desc" field.</summary>
    public const int DescFieldNumber = 9;
    private string desc_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Desc {
      get { return desc_; }
      set {
        desc_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Levels_Base);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Levels_Base other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ID != other.ID) return false;
      if(!allTyps_.Equals(other.allTyps_)) return false;
      if(!allNums_.Equals(other.allNums_)) return false;
      if(!afterTyps_.Equals(other.afterTyps_)) return false;
      if(!afterNum_.Equals(other.afterNum_)) return false;
      if(!triggerType_.Equals(other.triggerType_)) return false;
      if (Floor != other.Floor) return false;
      if (Name != other.Name) return false;
      if (Desc != other.Desc) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ID != 0) hash ^= ID.GetHashCode();
      hash ^= allTyps_.GetHashCode();
      hash ^= allNums_.GetHashCode();
      hash ^= afterTyps_.GetHashCode();
      hash ^= afterNum_.GetHashCode();
      hash ^= triggerType_.GetHashCode();
      if (Floor != 0) hash ^= Floor.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Desc.Length != 0) hash ^= Desc.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      allTyps_.WriteTo(output, _repeated_allTyps_codec);
      allNums_.WriteTo(output, _repeated_allNums_codec);
      afterTyps_.WriteTo(output, _repeated_afterTyps_codec);
      afterNum_.WriteTo(output, _repeated_afterNum_codec);
      triggerType_.WriteTo(output, _repeated_triggerType_codec);
      if (Floor != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Floor);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ID != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ID);
      }
      allTyps_.WriteTo(ref output, _repeated_allTyps_codec);
      allNums_.WriteTo(ref output, _repeated_allNums_codec);
      afterTyps_.WriteTo(ref output, _repeated_afterTyps_codec);
      afterNum_.WriteTo(ref output, _repeated_afterNum_codec);
      triggerType_.WriteTo(ref output, _repeated_triggerType_codec);
      if (Floor != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Floor);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Name);
      }
      if (Desc.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(Desc);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ID);
      }
      size += allTyps_.CalculateSize(_repeated_allTyps_codec);
      size += allNums_.CalculateSize(_repeated_allNums_codec);
      size += afterTyps_.CalculateSize(_repeated_afterTyps_codec);
      size += afterNum_.CalculateSize(_repeated_afterNum_codec);
      size += triggerType_.CalculateSize(_repeated_triggerType_codec);
      if (Floor != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Floor);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Desc.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Desc);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Levels_Base other) {
      if (other == null) {
        return;
      }
      if (other.ID != 0) {
        ID = other.ID;
      }
      allTyps_.Add(other.allTyps_);
      allNums_.Add(other.allNums_);
      afterTyps_.Add(other.afterTyps_);
      afterNum_.Add(other.afterNum_);
      triggerType_.Add(other.triggerType_);
      if (other.Floor != 0) {
        Floor = other.Floor;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Desc.Length != 0) {
        Desc = other.Desc;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            allTyps_.AddEntriesFrom(input, _repeated_allTyps_codec);
            break;
          }
          case 26:
          case 24: {
            allNums_.AddEntriesFrom(input, _repeated_allNums_codec);
            break;
          }
          case 34:
          case 32: {
            afterTyps_.AddEntriesFrom(input, _repeated_afterTyps_codec);
            break;
          }
          case 42:
          case 40: {
            afterNum_.AddEntriesFrom(input, _repeated_afterNum_codec);
            break;
          }
          case 50:
          case 48: {
            triggerType_.AddEntriesFrom(input, _repeated_triggerType_codec);
            break;
          }
          case 56: {
            Floor = input.ReadInt32();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
          case 74: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ID = input.ReadInt32();
            break;
          }
          case 18:
          case 16: {
            allTyps_.AddEntriesFrom(ref input, _repeated_allTyps_codec);
            break;
          }
          case 26:
          case 24: {
            allNums_.AddEntriesFrom(ref input, _repeated_allNums_codec);
            break;
          }
          case 34:
          case 32: {
            afterTyps_.AddEntriesFrom(ref input, _repeated_afterTyps_codec);
            break;
          }
          case 42:
          case 40: {
            afterNum_.AddEntriesFrom(ref input, _repeated_afterNum_codec);
            break;
          }
          case 50:
          case 48: {
            triggerType_.AddEntriesFrom(ref input, _repeated_triggerType_codec);
            break;
          }
          case 56: {
            Floor = input.ReadInt32();
            break;
          }
          case 66: {
            Name = input.ReadString();
            break;
          }
          case 74: {
            Desc = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Levels_Base_datas : pb::IMessage<Levels_Base_datas>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Levels_Base_datas> _parser = new pb::MessageParser<Levels_Base_datas>(() => new Levels_Base_datas());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Levels_Base_datas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.LevelsBase.LevelsBaseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base_datas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base_datas(Levels_Base_datas other) : this() {
      datamap_ = other.datamap_.Clone();
      datas_ = other.datas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Levels_Base_datas Clone() {
      return new Levels_Base_datas(this);
    }

    /// <summary>Field number for the "datamap" field.</summary>
    public const int DatamapFieldNumber = 1;
    private static readonly pbc::MapField<int, global::Config.LevelsBase.Levels_Base>.Codec _map_datamap_codec
        = new pbc::MapField<int, global::Config.LevelsBase.Levels_Base>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::Config.LevelsBase.Levels_Base.Parser), 10);
    private readonly pbc::MapField<int, global::Config.LevelsBase.Levels_Base> datamap_ = new pbc::MapField<int, global::Config.LevelsBase.Levels_Base>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::Config.LevelsBase.Levels_Base> Datamap {
      get { return datamap_; }
    }

    /// <summary>Field number for the "datas" field.</summary>
    public const int DatasFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Config.LevelsBase.Levels_Base> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(18, global::Config.LevelsBase.Levels_Base.Parser);
    private readonly pbc::RepeatedField<global::Config.LevelsBase.Levels_Base> datas_ = new pbc::RepeatedField<global::Config.LevelsBase.Levels_Base>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Config.LevelsBase.Levels_Base> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Levels_Base_datas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Levels_Base_datas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Datamap.Equals(other.Datamap)) return false;
      if(!datas_.Equals(other.datas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Datamap.GetHashCode();
      hash ^= datas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datamap_.WriteTo(output, _map_datamap_codec);
      datas_.WriteTo(output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datamap_.WriteTo(ref output, _map_datamap_codec);
      datas_.WriteTo(ref output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datamap_.CalculateSize(_map_datamap_codec);
      size += datas_.CalculateSize(_repeated_datas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Levels_Base_datas other) {
      if (other == null) {
        return;
      }
      datamap_.MergeFrom(other.datamap_);
      datas_.Add(other.datas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(ref input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(ref input, _repeated_datas_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
