// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Language_Base.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Config.LanguageBase {

  /// <summary>Holder for reflection information generated from Language_Base.proto</summary>
  public static partial class LanguageBaseReflection {

    #region Descriptor
    /// <summary>File descriptor for Language_Base.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LanguageBaseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNMYW5ndWFnZV9CYXNlLnByb3RvEhRDb25maWcuTGFuZ3VhZ2VfQmFzZSJX",
            "Cg1MYW5ndWFnZV9CYXNlEgwKBE5hbWUYASABKAkSDwoHemhfSGFucxgCIAEo",
            "CRIPCgd6aF9IYW50GAMgASgJEgoKAmVuGAQgASgJEgoKAmphGAUgASgJIucB",
            "ChNMYW5ndWFnZV9CYXNlX2RhdGFzEkcKB2RhdGFtYXAYASADKAsyNi5Db25m",
            "aWcuTGFuZ3VhZ2VfQmFzZS5MYW5ndWFnZV9CYXNlX2RhdGFzLkRhdGFtYXBF",
            "bnRyeRIyCgVkYXRhcxgCIAMoCzIjLkNvbmZpZy5MYW5ndWFnZV9CYXNlLkxh",
            "bmd1YWdlX0Jhc2UaUwoMRGF0YW1hcEVudHJ5EgsKA2tleRgBIAEoCRIyCgV2",
            "YWx1ZRgCIAEoCzIjLkNvbmZpZy5MYW5ndWFnZV9CYXNlLkxhbmd1YWdlX0Jh",
            "c2U6AjgBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.LanguageBase.Language_Base), global::Config.LanguageBase.Language_Base.Parser, new[]{ "Name", "ZhHans", "ZhHant", "En", "Ja" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Config.LanguageBase.Language_Base_datas), global::Config.LanguageBase.Language_Base_datas.Parser, new[]{ "Datamap", "Datas" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Language_Base : pb::IMessage<Language_Base>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Language_Base> _parser = new pb::MessageParser<Language_Base>(() => new Language_Base());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Language_Base> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.LanguageBase.LanguageBaseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base(Language_Base other) : this() {
      name_ = other.name_;
      zhHans_ = other.zhHans_;
      zhHant_ = other.zhHant_;
      en_ = other.en_;
      ja_ = other.ja_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base Clone() {
      return new Language_Base(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zh_Hans" field.</summary>
    public const int ZhHansFieldNumber = 2;
    private string zhHans_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ZhHans {
      get { return zhHans_; }
      set {
        zhHans_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "zh_Hant" field.</summary>
    public const int ZhHantFieldNumber = 3;
    private string zhHant_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ZhHant {
      get { return zhHant_; }
      set {
        zhHant_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "en" field.</summary>
    public const int EnFieldNumber = 4;
    private string en_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string En {
      get { return en_; }
      set {
        en_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ja" field.</summary>
    public const int JaFieldNumber = 5;
    private string ja_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Ja {
      get { return ja_; }
      set {
        ja_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Language_Base);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Language_Base other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (ZhHans != other.ZhHans) return false;
      if (ZhHant != other.ZhHant) return false;
      if (En != other.En) return false;
      if (Ja != other.Ja) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ZhHans.Length != 0) hash ^= ZhHans.GetHashCode();
      if (ZhHant.Length != 0) hash ^= ZhHant.GetHashCode();
      if (En.Length != 0) hash ^= En.GetHashCode();
      if (Ja.Length != 0) hash ^= Ja.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ZhHans.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ZhHans);
      }
      if (ZhHant.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ZhHant);
      }
      if (En.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(En);
      }
      if (Ja.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ja);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (ZhHans.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ZhHans);
      }
      if (ZhHant.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ZhHant);
      }
      if (En.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(En);
      }
      if (Ja.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Ja);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ZhHans.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ZhHans);
      }
      if (ZhHant.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ZhHant);
      }
      if (En.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(En);
      }
      if (Ja.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Ja);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Language_Base other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ZhHans.Length != 0) {
        ZhHans = other.ZhHans;
      }
      if (other.ZhHant.Length != 0) {
        ZhHant = other.ZhHant;
      }
      if (other.En.Length != 0) {
        En = other.En;
      }
      if (other.Ja.Length != 0) {
        Ja = other.Ja;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            ZhHans = input.ReadString();
            break;
          }
          case 26: {
            ZhHant = input.ReadString();
            break;
          }
          case 34: {
            En = input.ReadString();
            break;
          }
          case 42: {
            Ja = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            ZhHans = input.ReadString();
            break;
          }
          case 26: {
            ZhHant = input.ReadString();
            break;
          }
          case 34: {
            En = input.ReadString();
            break;
          }
          case 42: {
            Ja = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Language_Base_datas : pb::IMessage<Language_Base_datas>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Language_Base_datas> _parser = new pb::MessageParser<Language_Base_datas>(() => new Language_Base_datas());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Language_Base_datas> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Config.LanguageBase.LanguageBaseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base_datas() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base_datas(Language_Base_datas other) : this() {
      datamap_ = other.datamap_.Clone();
      datas_ = other.datas_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Language_Base_datas Clone() {
      return new Language_Base_datas(this);
    }

    /// <summary>Field number for the "datamap" field.</summary>
    public const int DatamapFieldNumber = 1;
    private static readonly pbc::MapField<string, global::Config.LanguageBase.Language_Base>.Codec _map_datamap_codec
        = new pbc::MapField<string, global::Config.LanguageBase.Language_Base>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Config.LanguageBase.Language_Base.Parser), 10);
    private readonly pbc::MapField<string, global::Config.LanguageBase.Language_Base> datamap_ = new pbc::MapField<string, global::Config.LanguageBase.Language_Base>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Config.LanguageBase.Language_Base> Datamap {
      get { return datamap_; }
    }

    /// <summary>Field number for the "datas" field.</summary>
    public const int DatasFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Config.LanguageBase.Language_Base> _repeated_datas_codec
        = pb::FieldCodec.ForMessage(18, global::Config.LanguageBase.Language_Base.Parser);
    private readonly pbc::RepeatedField<global::Config.LanguageBase.Language_Base> datas_ = new pbc::RepeatedField<global::Config.LanguageBase.Language_Base>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Config.LanguageBase.Language_Base> Datas {
      get { return datas_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Language_Base_datas);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Language_Base_datas other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Datamap.Equals(other.Datamap)) return false;
      if(!datas_.Equals(other.datas_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Datamap.GetHashCode();
      hash ^= datas_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      datamap_.WriteTo(output, _map_datamap_codec);
      datas_.WriteTo(output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      datamap_.WriteTo(ref output, _map_datamap_codec);
      datas_.WriteTo(ref output, _repeated_datas_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += datamap_.CalculateSize(_map_datamap_codec);
      size += datas_.CalculateSize(_repeated_datas_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Language_Base_datas other) {
      if (other == null) {
        return;
      }
      datamap_.MergeFrom(other.datamap_);
      datas_.Add(other.datas_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(input, _repeated_datas_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            datamap_.AddEntriesFrom(ref input, _map_datamap_codec);
            break;
          }
          case 18: {
            datas_.AddEntriesFrom(ref input, _repeated_datas_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
