// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtoGameData.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoGameData {

  /// <summary>Holder for reflection information generated from ProtoGameData.proto</summary>
  public static partial class ProtoGameDataReflection {

    #region Descriptor
    /// <summary>File descriptor for ProtoGameData.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoGameDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNQcm90b0dhbWVEYXRhLnByb3RvEg1Qcm90b0dhbWVEYXRhIjIKCVByb3Rv",
            "SXRlbRILCgNTaWQYASABKA0SCwoDQ2lkGAIgASgNEgsKA051bRgDIAEoDSJY",
            "ChJQcm90b0ludmVudG9yeUl0ZW0SEQoJSXRlbUxldmVsGAEgASgNEhAKCEl0",
            "ZW1UeXBlGAIgASgNEg4KBlVuTG9jaxgDIAEoCBINCgVJc091dBgEIAEoCCI0",
            "Cg1Qcm90b0l0ZW1Db3N0EhEKCUl0ZW1MZXZlbBgBIAEoDRIQCghJdGVtQ29z",
            "dBgCIAEoBCLtAQoNUHJvdG9Vc2VyRGF0YRILCgNVaWQYASABKA0SCwoDRXhw",
            "GAIgASgNEgwKBENvaW4YAyABKAQSDwoHRGlhbW9uZBgEIAEoDRISCgpDdXN0",
            "b21Db2luGAUgASgEEhEKCVNoYXJrVGltZRgGIAEoDRIQCghNYXhMZXZlbBgH",
            "IAEoDRI5Cg5JbnZlbnRvcnlJdGVtcxgIIAMoCzIhLlByb3RvR2FtZURhdGEu",
            "UHJvdG9JbnZlbnRvcnlJdGVtEi8KCUl0ZW1Db3N0cxgJIAMoCzIcLlByb3Rv",
            "R2FtZURhdGEuUHJvdG9JdGVtQ29zdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoGameData.ProtoItem), global::ProtoGameData.ProtoItem.Parser, new[]{ "Sid", "Cid", "Num" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoGameData.ProtoInventoryItem), global::ProtoGameData.ProtoInventoryItem.Parser, new[]{ "ItemLevel", "ItemType", "UnLock", "IsOut" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoGameData.ProtoItemCost), global::ProtoGameData.ProtoItemCost.Parser, new[]{ "ItemLevel", "ItemCost" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoGameData.ProtoUserData), global::ProtoGameData.ProtoUserData.Parser, new[]{ "Uid", "Exp", "Coin", "Diamond", "CustomCoin", "SharkTime", "MaxLevel", "InventoryItems", "ItemCosts" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProtoItem : pb::IMessage<ProtoItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoItem> _parser = new pb::MessageParser<ProtoItem>(() => new ProtoItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoGameData.ProtoGameDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItem(ProtoItem other) : this() {
      sid_ = other.sid_;
      cid_ = other.cid_;
      num_ = other.num_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItem Clone() {
      return new ProtoItem(this);
    }

    /// <summary>Field number for the "Sid" field.</summary>
    public const int SidFieldNumber = 1;
    private uint sid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Sid {
      get { return sid_; }
      set {
        sid_ = value;
      }
    }

    /// <summary>Field number for the "Cid" field.</summary>
    public const int CidFieldNumber = 2;
    private uint cid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Cid {
      get { return cid_; }
      set {
        cid_ = value;
      }
    }

    /// <summary>Field number for the "Num" field.</summary>
    public const int NumFieldNumber = 3;
    private uint num_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Num {
      get { return num_; }
      set {
        num_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Cid != other.Cid) return false;
      if (Num != other.Num) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Sid != 0) hash ^= Sid.GetHashCode();
      if (Cid != 0) hash ^= Cid.GetHashCode();
      if (Num != 0) hash ^= Num.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Sid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Sid);
      }
      if (Cid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cid);
      }
      if (Num != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Sid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Sid);
      }
      if (Cid != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cid);
      }
      if (Num != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Num);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Sid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Sid);
      }
      if (Cid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Cid);
      }
      if (Num != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Num);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoItem other) {
      if (other == null) {
        return;
      }
      if (other.Sid != 0) {
        Sid = other.Sid;
      }
      if (other.Cid != 0) {
        Cid = other.Cid;
      }
      if (other.Num != 0) {
        Num = other.Num;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Sid = input.ReadUInt32();
            break;
          }
          case 16: {
            Cid = input.ReadUInt32();
            break;
          }
          case 24: {
            Num = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Sid = input.ReadUInt32();
            break;
          }
          case 16: {
            Cid = input.ReadUInt32();
            break;
          }
          case 24: {
            Num = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtoInventoryItem : pb::IMessage<ProtoInventoryItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoInventoryItem> _parser = new pb::MessageParser<ProtoInventoryItem>(() => new ProtoInventoryItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoInventoryItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoGameData.ProtoGameDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoInventoryItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoInventoryItem(ProtoInventoryItem other) : this() {
      itemLevel_ = other.itemLevel_;
      itemType_ = other.itemType_;
      unLock_ = other.unLock_;
      isOut_ = other.isOut_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoInventoryItem Clone() {
      return new ProtoInventoryItem(this);
    }

    /// <summary>Field number for the "ItemLevel" field.</summary>
    public const int ItemLevelFieldNumber = 1;
    private uint itemLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemLevel {
      get { return itemLevel_; }
      set {
        itemLevel_ = value;
      }
    }

    /// <summary>Field number for the "ItemType" field.</summary>
    public const int ItemTypeFieldNumber = 2;
    private uint itemType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemType {
      get { return itemType_; }
      set {
        itemType_ = value;
      }
    }

    /// <summary>Field number for the "UnLock" field.</summary>
    public const int UnLockFieldNumber = 3;
    private bool unLock_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool UnLock {
      get { return unLock_; }
      set {
        unLock_ = value;
      }
    }

    /// <summary>Field number for the "IsOut" field.</summary>
    public const int IsOutFieldNumber = 4;
    private bool isOut_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOut {
      get { return isOut_; }
      set {
        isOut_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoInventoryItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoInventoryItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemLevel != other.ItemLevel) return false;
      if (ItemType != other.ItemType) return false;
      if (UnLock != other.UnLock) return false;
      if (IsOut != other.IsOut) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemLevel != 0) hash ^= ItemLevel.GetHashCode();
      if (ItemType != 0) hash ^= ItemType.GetHashCode();
      if (UnLock != false) hash ^= UnLock.GetHashCode();
      if (IsOut != false) hash ^= IsOut.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemLevel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ItemLevel);
      }
      if (ItemType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ItemType);
      }
      if (UnLock != false) {
        output.WriteRawTag(24);
        output.WriteBool(UnLock);
      }
      if (IsOut != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemLevel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ItemLevel);
      }
      if (ItemType != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(ItemType);
      }
      if (UnLock != false) {
        output.WriteRawTag(24);
        output.WriteBool(UnLock);
      }
      if (IsOut != false) {
        output.WriteRawTag(32);
        output.WriteBool(IsOut);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemLevel);
      }
      if (ItemType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemType);
      }
      if (UnLock != false) {
        size += 1 + 1;
      }
      if (IsOut != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoInventoryItem other) {
      if (other == null) {
        return;
      }
      if (other.ItemLevel != 0) {
        ItemLevel = other.ItemLevel;
      }
      if (other.ItemType != 0) {
        ItemType = other.ItemType;
      }
      if (other.UnLock != false) {
        UnLock = other.UnLock;
      }
      if (other.IsOut != false) {
        IsOut = other.IsOut;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemLevel = input.ReadUInt32();
            break;
          }
          case 16: {
            ItemType = input.ReadUInt32();
            break;
          }
          case 24: {
            UnLock = input.ReadBool();
            break;
          }
          case 32: {
            IsOut = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemLevel = input.ReadUInt32();
            break;
          }
          case 16: {
            ItemType = input.ReadUInt32();
            break;
          }
          case 24: {
            UnLock = input.ReadBool();
            break;
          }
          case 32: {
            IsOut = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtoItemCost : pb::IMessage<ProtoItemCost>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoItemCost> _parser = new pb::MessageParser<ProtoItemCost>(() => new ProtoItemCost());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoItemCost> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoGameData.ProtoGameDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItemCost() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItemCost(ProtoItemCost other) : this() {
      itemLevel_ = other.itemLevel_;
      itemCost_ = other.itemCost_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoItemCost Clone() {
      return new ProtoItemCost(this);
    }

    /// <summary>Field number for the "ItemLevel" field.</summary>
    public const int ItemLevelFieldNumber = 1;
    private uint itemLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint ItemLevel {
      get { return itemLevel_; }
      set {
        itemLevel_ = value;
      }
    }

    /// <summary>Field number for the "ItemCost" field.</summary>
    public const int ItemCostFieldNumber = 2;
    private ulong itemCost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ItemCost {
      get { return itemCost_; }
      set {
        itemCost_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoItemCost);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoItemCost other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemLevel != other.ItemLevel) return false;
      if (ItemCost != other.ItemCost) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemLevel != 0) hash ^= ItemLevel.GetHashCode();
      if (ItemCost != 0UL) hash ^= ItemCost.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ItemLevel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ItemLevel);
      }
      if (ItemCost != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ItemCost);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ItemLevel != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(ItemLevel);
      }
      if (ItemCost != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ItemCost);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ItemLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(ItemLevel);
      }
      if (ItemCost != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ItemCost);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoItemCost other) {
      if (other == null) {
        return;
      }
      if (other.ItemLevel != 0) {
        ItemLevel = other.ItemLevel;
      }
      if (other.ItemCost != 0UL) {
        ItemCost = other.ItemCost;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemLevel = input.ReadUInt32();
            break;
          }
          case 16: {
            ItemCost = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ItemLevel = input.ReadUInt32();
            break;
          }
          case 16: {
            ItemCost = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class ProtoUserData : pb::IMessage<ProtoUserData>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoUserData> _parser = new pb::MessageParser<ProtoUserData>(() => new ProtoUserData());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoUserData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoGameData.ProtoGameDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoUserData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoUserData(ProtoUserData other) : this() {
      uid_ = other.uid_;
      exp_ = other.exp_;
      coin_ = other.coin_;
      diamond_ = other.diamond_;
      customCoin_ = other.customCoin_;
      sharkTime_ = other.sharkTime_;
      maxLevel_ = other.maxLevel_;
      inventoryItems_ = other.inventoryItems_.Clone();
      itemCosts_ = other.itemCosts_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoUserData Clone() {
      return new ProtoUserData(this);
    }

    /// <summary>Field number for the "Uid" field.</summary>
    public const int UidFieldNumber = 1;
    private uint uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Uid {
      get { return uid_; }
      set {
        uid_ = value;
      }
    }

    /// <summary>Field number for the "Exp" field.</summary>
    public const int ExpFieldNumber = 2;
    private uint exp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Exp {
      get { return exp_; }
      set {
        exp_ = value;
      }
    }

    /// <summary>Field number for the "Coin" field.</summary>
    public const int CoinFieldNumber = 3;
    private ulong coin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Coin {
      get { return coin_; }
      set {
        coin_ = value;
      }
    }

    /// <summary>Field number for the "Diamond" field.</summary>
    public const int DiamondFieldNumber = 4;
    private uint diamond_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Diamond {
      get { return diamond_; }
      set {
        diamond_ = value;
      }
    }

    /// <summary>Field number for the "CustomCoin" field.</summary>
    public const int CustomCoinFieldNumber = 5;
    private ulong customCoin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CustomCoin {
      get { return customCoin_; }
      set {
        customCoin_ = value;
      }
    }

    /// <summary>Field number for the "SharkTime" field.</summary>
    public const int SharkTimeFieldNumber = 6;
    private uint sharkTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SharkTime {
      get { return sharkTime_; }
      set {
        sharkTime_ = value;
      }
    }

    /// <summary>Field number for the "MaxLevel" field.</summary>
    public const int MaxLevelFieldNumber = 7;
    private uint maxLevel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxLevel {
      get { return maxLevel_; }
      set {
        maxLevel_ = value;
      }
    }

    /// <summary>Field number for the "InventoryItems" field.</summary>
    public const int InventoryItemsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::ProtoGameData.ProtoInventoryItem> _repeated_inventoryItems_codec
        = pb::FieldCodec.ForMessage(66, global::ProtoGameData.ProtoInventoryItem.Parser);
    private readonly pbc::RepeatedField<global::ProtoGameData.ProtoInventoryItem> inventoryItems_ = new pbc::RepeatedField<global::ProtoGameData.ProtoInventoryItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoGameData.ProtoInventoryItem> InventoryItems {
      get { return inventoryItems_; }
    }

    /// <summary>Field number for the "ItemCosts" field.</summary>
    public const int ItemCostsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::ProtoGameData.ProtoItemCost> _repeated_itemCosts_codec
        = pb::FieldCodec.ForMessage(74, global::ProtoGameData.ProtoItemCost.Parser);
    private readonly pbc::RepeatedField<global::ProtoGameData.ProtoItemCost> itemCosts_ = new pbc::RepeatedField<global::ProtoGameData.ProtoItemCost>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoGameData.ProtoItemCost> ItemCosts {
      get { return itemCosts_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoUserData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoUserData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (Exp != other.Exp) return false;
      if (Coin != other.Coin) return false;
      if (Diamond != other.Diamond) return false;
      if (CustomCoin != other.CustomCoin) return false;
      if (SharkTime != other.SharkTime) return false;
      if (MaxLevel != other.MaxLevel) return false;
      if(!inventoryItems_.Equals(other.inventoryItems_)) return false;
      if(!itemCosts_.Equals(other.itemCosts_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Uid != 0) hash ^= Uid.GetHashCode();
      if (Exp != 0) hash ^= Exp.GetHashCode();
      if (Coin != 0UL) hash ^= Coin.GetHashCode();
      if (Diamond != 0) hash ^= Diamond.GetHashCode();
      if (CustomCoin != 0UL) hash ^= CustomCoin.GetHashCode();
      if (SharkTime != 0) hash ^= SharkTime.GetHashCode();
      if (MaxLevel != 0) hash ^= MaxLevel.GetHashCode();
      hash ^= inventoryItems_.GetHashCode();
      hash ^= itemCosts_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Uid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uid);
      }
      if (Exp != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Exp);
      }
      if (Coin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Coin);
      }
      if (Diamond != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Diamond);
      }
      if (CustomCoin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(CustomCoin);
      }
      if (SharkTime != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(SharkTime);
      }
      if (MaxLevel != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MaxLevel);
      }
      inventoryItems_.WriteTo(output, _repeated_inventoryItems_codec);
      itemCosts_.WriteTo(output, _repeated_itemCosts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Uid != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Uid);
      }
      if (Exp != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Exp);
      }
      if (Coin != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Coin);
      }
      if (Diamond != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Diamond);
      }
      if (CustomCoin != 0UL) {
        output.WriteRawTag(40);
        output.WriteUInt64(CustomCoin);
      }
      if (SharkTime != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(SharkTime);
      }
      if (MaxLevel != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MaxLevel);
      }
      inventoryItems_.WriteTo(ref output, _repeated_inventoryItems_codec);
      itemCosts_.WriteTo(ref output, _repeated_itemCosts_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Uid != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Uid);
      }
      if (Exp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Exp);
      }
      if (Coin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Coin);
      }
      if (Diamond != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Diamond);
      }
      if (CustomCoin != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CustomCoin);
      }
      if (SharkTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SharkTime);
      }
      if (MaxLevel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxLevel);
      }
      size += inventoryItems_.CalculateSize(_repeated_inventoryItems_codec);
      size += itemCosts_.CalculateSize(_repeated_itemCosts_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoUserData other) {
      if (other == null) {
        return;
      }
      if (other.Uid != 0) {
        Uid = other.Uid;
      }
      if (other.Exp != 0) {
        Exp = other.Exp;
      }
      if (other.Coin != 0UL) {
        Coin = other.Coin;
      }
      if (other.Diamond != 0) {
        Diamond = other.Diamond;
      }
      if (other.CustomCoin != 0UL) {
        CustomCoin = other.CustomCoin;
      }
      if (other.SharkTime != 0) {
        SharkTime = other.SharkTime;
      }
      if (other.MaxLevel != 0) {
        MaxLevel = other.MaxLevel;
      }
      inventoryItems_.Add(other.inventoryItems_);
      itemCosts_.Add(other.itemCosts_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadUInt32();
            break;
          }
          case 16: {
            Exp = input.ReadUInt32();
            break;
          }
          case 24: {
            Coin = input.ReadUInt64();
            break;
          }
          case 32: {
            Diamond = input.ReadUInt32();
            break;
          }
          case 40: {
            CustomCoin = input.ReadUInt64();
            break;
          }
          case 48: {
            SharkTime = input.ReadUInt32();
            break;
          }
          case 56: {
            MaxLevel = input.ReadUInt32();
            break;
          }
          case 66: {
            inventoryItems_.AddEntriesFrom(input, _repeated_inventoryItems_codec);
            break;
          }
          case 74: {
            itemCosts_.AddEntriesFrom(input, _repeated_itemCosts_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadUInt32();
            break;
          }
          case 16: {
            Exp = input.ReadUInt32();
            break;
          }
          case 24: {
            Coin = input.ReadUInt64();
            break;
          }
          case 32: {
            Diamond = input.ReadUInt32();
            break;
          }
          case 40: {
            CustomCoin = input.ReadUInt64();
            break;
          }
          case 48: {
            SharkTime = input.ReadUInt32();
            break;
          }
          case 56: {
            MaxLevel = input.ReadUInt32();
            break;
          }
          case 66: {
            inventoryItems_.AddEntriesFrom(ref input, _repeated_inventoryItems_codec);
            break;
          }
          case 74: {
            itemCosts_.AddEntriesFrom(ref input, _repeated_itemCosts_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
